const CONFIG = {
    // Canvas & Blocos
    CANVAS_LARGURA: 800,
    CANVAS_ALTURA: 600,
    LARGURA_BLOCO: 40,
    ALTURA_BLOCO: 40,

    // Jogo
    MAX_VIDAS: 10,
    MAX_NIVEIS: 15,
    INVENCIBILIDADE_FRAMES: 60,
    MORTE_INSTANTANEA_DELAY: 10,
    MORTE_POR_QUEDA_Y_OFFSET: 200,

    // Física do Jogador
    PLAYER_SPEED_X: 5,
    GRAVITY: 0.8,
    JUMP_FORCE: 15,
    MAX_JUMPS: 2,

    // Visuais e Itens
    PORTAL_LARGURA: 100,
    PORTAL_ALTURA: 10,
    PORTAL_SHADOW_BLUR: 20,
    PORTAL_COOLDOWN_FRAMES: 30,
    PORTA_LARGURA: 80,
    PORTA_ALTURA: 100,
    PORTA_LARGURA_BASE: 70,
    PORTA_ALTURA_BASE: 60,
    PORTA_X_OFFSET: 120,
    PORTA_BRILHO_SHADOW_BLUR: 30,
    PORTA_BRILHO_RAIO_BASE: 25,
    PORTA_BRILHO_RAIO_ANIM: 8,
    PORTA_BRILHO_ANIM_SPEED: 0.1,
    CHAVE_TAMANHO: 20,
    ESPINHO_ALTURA: 20,
    ESPINHO_DENTE_LARGURA: 10,
    ESPINHO_LINE_WIDTH: 4,
    ESPINHO_SHADOW_LINE_WIDTH: 2,
    CORACAO_TAMANHO: 20,
    CORACAO_REFLEXO_ROTATION_DEGREES: -15,

    // Geração Aleatória de Corações
    CHANCE_CORACAO_INICIAL: 0.25,
    CHANCE_CORACAO_INCREMENTO_POR_NIVEL: 0.02,
    CORACAO_GERACAO_TENTATIVAS: 5,
    CORACAO_GERACAO_X_PADDING: 50,
    CORACAO_GERACAO_Y_MIN: 100,
    CORACAO_GERACAO_Y_MAX_OFFSET: 350,
    CORACAO_GERACAO_OVERLAP_MARGIN: 50,

    // Efeitos Visuais
    NUM_ESTRELAS_PERTO: 50,
    NUM_ESTRELAS_LONGE: 150,
    LUA_X_OFFSET: 120,
    LUA_Y: 100,
    LUA_RAIO: 50,
    LUA_HALO_SIZE_MULT: 2,
    RASTRO_COMPRIMENTO: 20,

    // Partículas
    MORTE_PARTICULAS: 30,
    POEIRA_MAX_PARTICULAS: 25,
    POEIRA_IMPACTO_MINIMO: 8,
    CURA_PARTICULAS: 20,

    // Cores
    CORES: {
        CURA_RGB: "244, 63, 94",
        JOGADOR: "#a7d1fa",
        JOGADOR_RASTRO_RGB: "138, 184, 255",
        BLOCO: "#475569",
        BLOCO_GRAD_TOP: "#64748b",
        ESPINHO: "#a78bfa",
        CHAVE: "#a5f3fc",
        PORTA_FECHADA: "#312e81",
        PORTA_ABERTA: "#c026d3",
        PORTA_STROKE_COR: "rgba(0, 0, 0, 0.2)",
        PORTAL: "orange",
        PORTAL_BRILHO: "yellow",
        CORACAO: "#f43f5e",
        LUA_CLARA: "#f0f9ff",
        LUA_COR_INTERNA: "#b0b0b0",
        LUA_HALO: "rgba(167, 209, 250, 0.1)",
        POEIRA_RGB: "203, 213, 225",
        MORTE_RGB: "167, 209, 250",
        CENARIO_GRAD_COR_1: "#010A1A",
        CENARIO_GRAD_COR_2: "#002040",
        CENARIO_GRAD_COR_3: "#004B7D",
        CHAO_GRAD_COR_1: "#253D3D",
        CHAO_GRAD_COR_2: "#152525",
    }
};

CONFIG.CHAO_Y = CONFIG.CANVAS_ALTURA - CONFIG.ALTURA_BLOCO;
CONFIG.PLAYER_LARGURA = CONFIG.LARGURA_BLOCO * 0.8;
CONFIG.PLAYER_ALTURA = CONFIG.LARGURA_BLOCO * 0.8;
CONFIG.PLAYER_RAIO = CONFIG.PLAYER_LARGURA / 2;
